
'use client'

import { useEffect, useMemo, useState } from 'react'
import { supabase, API } from '@/lib/supabase'

const money = (v:any)=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(v||0))
const today=()=>new Date().toISOString().slice(0,10)
const plus14=()=>new Date(Date.now()+12096e5).toISOString().slice(0,10)
const packageTools:any={
  Starter:['reviews','qr','reports','tickets'],
  Growth:['reviews','qr','reports','tickets','seo','booking','invoices'],
  Premium:['reviews','qr','reports','tickets','seo','booking','invoices','integrations','templates','goals','multi_locations'],
  Individuell:[]
}
const toolView:any={seo:'seo',booking:'booking',tickets:'customerTickets',invoices:'customerFinance',integrations:'integrations',templates:'templates',reviews:'growth',qr:'growth',reports:'growth',goals:'goals',multi_locations:'locations'}

function Hero({title,text}:any){return <div className="hero"><h1>{title}</h1><p>{text}</p></div>}
function Card({title,children}:any){return <section className="card">{title&&<h2>{title}</h2>}{children}</section>}
function Modal({title,onClose,children}:any){return <div className="modalBg"><div className="modal"><div className="row between"><h2>{title}</h2><button className="btn secondary" onClick={onClose}>×</button></div>{children}</div></div>}
function weekDays(offset=0){const d=new Date();const day=d.getDay()||7;d.setDate(d.getDate()-day+1+offset*7);return Array.from({length:7},(_,i)=>{const x=new Date(d);x.setDate(d.getDate()+i);return{iso:x.toISOString().slice(0,10),label:x.toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'2-digit'})}})}

export default function Page(){
  const[session,setSession]=useState<any>(null),[profile,setProfile]=useState<any>(null),[customers,setCustomers]=useState<any[]>([])
  const[activeCustomer,setActiveCustomer]=useState<any>(null),[customerEnv,setCustomerEnv]=useState(false),[view,setView]=useState('dashboard'),[theme,setTheme]=useState('purple')
  const[enabledViews,setEnabledViews]=useState<string[]>([]),[showLogin,setShowLogin]=useState(false)

  useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:sub}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>sub.subscription.unsubscribe()},[])
  useEffect(()=>{if(session?.user)loadBase()},[session])
  useEffect(()=>{if(activeCustomer)loadToolViews(activeCustomer.id);else setEnabledViews([])},[activeCustomer])

  async function loadBase(){
    const{data:prof}=await supabase.from('profiles').select('*').eq('id',session.user.id).single()
    setProfile(prof)
    if(['admin','employee','support','sales','seo_manager','buchhaltung'].includes(prof?.role)){
      const{data}=await supabase.from('customers').select('*').order('created_at',{ascending:false})
      setCustomers(data||[]);setActiveCustomer((data||[])[0]||null);setCustomerEnv(false);setView('dashboard')
    }else{
      const{data}=await supabase.from('user_customer_access').select('customers(*)').eq('user_id',session.user.id)
      const list=(data||[]).map((x:any)=>x.customers).filter(Boolean)
      setCustomers(list);setActiveCustomer(list[0]||null);setCustomerEnv(true);setView('customerDashboard')
    }
  }
  async function loadToolViews(cid:string){
    const{data}=await supabase.from('customer_tool_access').select('*').eq('customer_id',cid).eq('enabled',true)
    setEnabledViews([...new Set((data||[]).map((x:any)=>toolView[x.tool_key]).filter(Boolean))] as string[])
  }
  async function logout(){await supabase.auth.signOut();setSession(null);setProfile(null)}
  function enterCustomer(c:any){setActiveCustomer(c);setCustomerEnv(true);setView('customerDashboard')}
  function backAdmin(){setCustomerEnv(false);setView('dashboard')}

  if(!session) return showLogin?<Login onSession={setSession}/>:<Landing onOpen={()=>setShowLogin(true)}/>
  if(!profile)return <main className="login"><div className="loginBox"><h1>Lade Profil...</h1></div></main>

  const adminViews=['dashboard','crm','onboarding','finance','seoControl','pipeline','operations','automations','notifications','search','theme','audit']
  const baseCustomerViews=['customerDashboard']
  const customerViews=[...new Set([...baseCustomerViews,...enabledViews])]
  const views=customerEnv?customerViews:adminViews
  return <div data-theme={theme} className="app"><aside className="side"><div className="brand">MMOS v10<br/><small>Enterprise MVP</small></div><div className="profile"><b>{profile.full_name||profile.email}</b><br/><small>{profile.role}</small>{activeCustomer&&<><br/><small>{customerEnv?'Kunde':'Aktiv'}: {activeCustomer.name}</small></>}</div>{customerEnv&&profile.role!=='customer'&&<button className="nav active" onClick={backAdmin}>← Adminbereich</button>}{views.map(v=><button key={v} className={view===v?'nav active':'nav'} onClick={()=>setView(v)}>{label(v)}</button>)}<button className="nav" onClick={()=>setTheme(theme==='purple'?'executive':'purple')}>🎨 Theme wechseln</button><button className="nav red" onClick={logout}>Logout</button></aside><main className="main">
    {!customerEnv&&view==='dashboard'&&<AdminDashboard customers={customers}/>}
    {!customerEnv&&view==='crm'&&<CRM customers={customers} reload={loadBase} enterCustomer={enterCustomer}/>}
    {!customerEnv&&view==='onboarding'&&<OnboardingAdmin customers={customers}/>} 
    {!customerEnv&&view==='finance'&&<Finance customers={customers}/>}
    {!customerEnv&&view==='seoControl'&&<SEOControl customers={customers}/>}
    {!customerEnv&&view==='pipeline'&&<Pipeline customers={customers}/>}
    {!customerEnv&&view==='operations'&&<Operations customers={customers}/>}
    {!customerEnv&&view==='automations'&&<Automations/>}
    {!customerEnv&&view==='notifications'&&<Notifications/>}
    {!customerEnv&&view==='search'&&<GlobalSearch/>}
    {!customerEnv&&view==='theme'&&<ThemeCenter theme={theme} setTheme={setTheme}/>}
    {!customerEnv&&view==='audit'&&<Audit/>}
    {customerEnv&&view==='customerDashboard'&&<CustomerDashboard customer={activeCustomer}/>}
    {customerEnv&&view==='seo'&&<CustomerSEO customer={activeCustomer}/>}
    {customerEnv&&view==='booking'&&<Booking customer={activeCustomer}/>}
    {customerEnv&&view==='customerTickets'&&<CustomerTickets customer={activeCustomer} profile={profile}/>}
    {customerEnv&&view==='customerFinance'&&<CustomerFinance customer={activeCustomer}/>}
    {customerEnv&&view==='goals'&&<Goals customer={activeCustomer}/>}
    {customerEnv&&view==='growth'&&<Growth customer={activeCustomer}/>}
    {customerEnv&&view==='integrations'&&<Integrations customer={activeCustomer}/>}
    {customerEnv&&view==='locations'&&<Locations customer={activeCustomer}/>}
    {customerEnv&&view==='templates'&&<Templates/>}
  </main></div>
}

function label(v:string){return ({dashboard:'📊 Dashboard',crm:'🏢 CRM Suite',onboarding:'🧾 Onboarding',finance:'💶 Finance',seoControl:'📈 SEO Control',pipeline:'💰 Pipeline',operations:'🎫 Operations',automations:'⚙️ Automationen',notifications:'🔔 Notifications',search:'🔎 Global Search',theme:'🎨 Design',audit:'🕵️ Audit',customerDashboard:'🏠 Dashboard',seo:'📈 SEO',booking:'🗓️ Booking',customerTickets:'🎫 Support',customerFinance:'💶 Finanzen',goals:'🎯 Ziele',growth:'🚀 Growth',integrations:'🔌 Integrationen',locations:'📍 Standorte',templates:'✉️ Vorlagen'} as any)[v]||v}

function Landing({onOpen}:any){return <main className="landing"><nav><b>Mecklenburg Marketing OS</b><button className="btn secondary" onClick={onOpen}>Login und registrieren</button></nav><h1>MMOS v10 Enterprise</h1><p>Funktionsfähiges MVP mit Supabase Auth, CRM, Finance, SEO, Booking, Tickets, Tool-Freischaltung, Notifications und Timeline.</p><div style={{textAlign:'center'}}><button className="btn" onClick={onOpen}>Jetzt einloggen</button></div><div className="landingGrid"><div>CRM Suite</div><div>SEO Control</div><div>Finance</div><div>Automationen</div></div></main>}
function Login({onSession}:any){const[email,setEmail]=useState('admin@agentur.local'),[password,setPassword]=useState(''),[err,setErr]=useState(''),[reg,setReg]=useState(false);async function login(){const{data,error}=await supabase.auth.signInWithPassword({email,password});if(error)return setErr(error.message);onSession(data.session)}if(reg)return <Register onBack={()=>setReg(false)} onSession={onSession}/>;return <main className="login"><div className="loginBox"><h1>MMOS Login</h1><input className="input" value={email} onChange={e=>setEmail(e.target.value)} placeholder="E-Mail"/><input className="input" value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Passwort"/>{err&&<p style={{color:'#dc2626'}}>{err}</p>}<button className="btn" onClick={login}>Einloggen</button><button className="btn secondary" onClick={()=>setReg(true)}>Registrieren</button><p className="muted">Demo nach Bootstrap: admin@agentur.local / AdminDemo123!</p></div></main>}
function Register({onBack,onSession}:any){const[form,setForm]=useState({business_name:'',branch:'',contact_name:'',email:'',phone:'',password:'',package_name:'Starter'}),[err,setErr]=useState('');async function submit(){const res=await fetch(API+'/api/onboarding/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const data=await res.json();if(!res.ok)return setErr(data.error||'Registrierung fehlgeschlagen');const login=await supabase.auth.signInWithPassword({email:form.email,password:form.password});if(login.error)return setErr(login.error.message);onSession(login.data.session)}return <main className="login"><div className="loginBox"><h1>Registrieren</h1><input className="input" placeholder="Betriebsname" value={form.business_name} onChange={e=>setForm({...form,business_name:e.target.value})}/><input className="input" placeholder="Branche" value={form.branch} onChange={e=>setForm({...form,branch:e.target.value})}/><input className="input" placeholder="Kontaktperson" value={form.contact_name} onChange={e=>setForm({...form,contact_name:e.target.value})}/><input className="input" placeholder="E-Mail" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input className="input" placeholder="Telefon" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input className="input" type="password" placeholder="Passwort" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><select className="input" value={form.package_name} onChange={e=>setForm({...form,package_name:e.target.value})}><option>Starter</option><option>Growth</option><option>Premium</option></select>{err&&<p style={{color:'#dc2626'}}>{err}</p>}<button className="btn" onClick={submit}>Registrieren & einloggen</button><button className="btn secondary" onClick={onBack}>Zurück</button></div></main>}

function AdminDashboard({customers}:any){const[offers,setOffers]=useState<any[]>([]),[tickets,setTickets]=useState<any[]>([]),[invoices,setInvoices]=useState<any[]>([]),[notes,setNotes]=useState<any[]>([]);useEffect(()=>{supabase.from('offers').select('*').then(({data})=>setOffers(data||[]));supabase.from('tickets').select('*,customers(*)').order('created_at',{ascending:false}).limit(6).then(({data})=>setTickets(data||[]));supabase.from('invoices').select('*,customers(*)').neq('status','Bezahlt').limit(6).then(({data})=>setInvoices(data||[]));supabase.from('notifications').select('*,customers(*)').order('created_at',{ascending:false}).limit(6).then(({data})=>setNotes(data||[]))},[]);const revenue=offers.filter(o=>['Angenommen','Beauftragt','Gewonnen'].includes(o.status)).reduce((s,o)=>s+Number(o.amount||0),0);return <><Hero title="Enterprise Dashboard" text="Live Cockpit für CRM, Umsatz, Tickets, Rechnungen und Notifications."/><div className="grid4"><Card title="Kunden"><div className="kpi">{customers.length}</div></Card><Card title="Monatsumsatz"><div className="kpi">{money(revenue)}</div></Card><Card title="Offene Rechnungen"><div className="kpi">{invoices.length}</div></Card><Card title="Tickets"><div className="kpi">{tickets.length}</div></Card></div><div className="grid2"><Card title="Notifications">{notes.map(n=><div className="item" key={n.id}><b>{n.title}</b><br/>{n.customers?.name}<p>{n.message}</p></div>)}</Card><Card title="Operations Feed">{tickets.map(t=><div className="item" key={t.id}>{t.customers?.name}: {t.title}<br/><span className="badge">{t.status}</span></div>)}</Card></div></>}
function CRM({customers,reload,enterCustomer}:any){const[selected,setSelected]=useState<any>(null);if(selected)return <CustomerFile customer={selected} onBack={()=>setSelected(null)} reload={reload} enterCustomer={enterCustomer}/>;return <><Hero title="CRM Suite" text="Kunden, Lifecycle, 360° Akte, Angebote, Tools und Verträge."/><Card title="Kunden"><table className="table"><tbody>{customers.map((c:any)=><tr key={c.id}><td><button className="btn secondary" onClick={()=>setSelected(c)}>{c.name}</button><br/><small>{c.branch}</small></td><td>{c.email}</td><td>{c.status}</td><td><button className="btn" onClick={()=>enterCustomer(c)}>Kundenportal</button></td></tr>)}</tbody></table></Card></>}
function CustomerFile({customer,onBack,reload,enterCustomer}:any){const[tab,setTab]=useState('overview');const tabs=['overview','timeline','offers','contracts','finance','seo','tickets','tools'];return <><button className="btn secondary" onClick={onBack}>← Zurück</button><Hero title={customer.name} text={`${customer.branch||'-'} · ${customer.email||'-'}`}/><div className="tabs">{tabs.map(t=><button key={t} className={tab===t?'btn':'btn secondary'} onClick={()=>setTab(t)}>{t}</button>)}<button className="btn" onClick={()=>enterCustomer(customer)}>Kundenportal öffnen</button></div>{tab==='overview'&&<div className="grid3"><Card title="Status"><div className="kpi">{customer.status}</div></Card><Card title="Rating"><div className="kpi">{customer.rating||0}★</div></Card><Card title="Lifecycle"><div className="kpi">{customer.lifecycle_status||'Lead'}</div></Card></div>}{tab==='timeline'&&<Timeline customer={customer}/>} {tab==='offers'&&<Offers customer={customer}/>} {tab==='contracts'&&<Contracts customer={customer}/>} {tab==='finance'&&<Finance customers={[customer]} customer={customer}/>} {tab==='seo'&&<SEOControl customers={[customer]} customer={customer}/>} {tab==='tickets'&&<Operations customer={customer}/>} {tab==='tools'&&<ToolAccess customer={customer}/>}</>}
function Timeline({customer}:any){const[items,setItems]=useState<any[]>([]),[title,setTitle]=useState('');useEffect(()=>{load()},[customer]);async function load(){const{data}=await supabase.from('activity_logs').select('*').eq('customer_id',customer.id).order('created_at',{ascending:false});setItems(data||[])}async function add(){await supabase.from('activity_logs').insert({customer_id:customer.id,event_type:'note',title,description:'Manueller Admin Eintrag'});setTitle('');load()}return <div className="grid2"><Card title="Eintrag"><input className="input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Titel"/><button className="btn" onClick={add}>Speichern</button></Card><Card title="Timeline"><div className="scroll">{items.map(i=><div className="item" key={i.id}>{i.title}<br/><small>{i.event_type} · {new Date(i.created_at).toLocaleString('de-DE')}</small><p>{i.description}</p></div>)}</div></Card></div>}
function Offers({customer}:any){const[items,setItems]=useState<any[]>([]),[form,setForm]=useState({title:'',amount:499,status:'Offen',package_name:'Growth'});useEffect(()=>{load()},[customer]);async function load(){const{data}=await supabase.from('offers').select('*').eq('customer_id',customer.id).order('created_at',{ascending:false});setItems(data||[])}async function unlock(pkg:string){for(const tool_key of packageTools[pkg]||[]){await supabase.from('customer_tool_access').upsert({customer_id:customer.id,tool_key,enabled:true,source_package:pkg},{onConflict:'customer_id,tool_key'})}}async function save(){await supabase.from('offers').insert({offer_number:'ANG-'+Date.now(),customer_id:customer.id,...form});if(['Angenommen','Beauftragt','Gewonnen'].includes(form.status))await unlock(form.package_name);await supabase.from('activity_logs').insert({customer_id:customer.id,event_type:'offer',title:'Angebot erstellt',description:form.title,entity:'offers'});await supabase.from('notifications').insert({customer_id:customer.id,title:'Angebot erstellt',message:form.title,type:'offer',target_view:'offers'});load()}async function update(i:any,status:string){await supabase.from('offers').update({status}).eq('id',i.id);if(['Angenommen','Beauftragt','Gewonnen'].includes(status))await unlock(i.package_name||'Growth');load()}return <div className="grid2"><Card title="Angebot"><input className="input" placeholder="Titel" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input className="input" type="number" value={form.amount} onChange={e=>setForm({...form,amount:Number(e.target.value)})}/><select className="input" value={form.package_name} onChange={e=>setForm({...form,package_name:e.target.value})}><option>Starter</option><option>Growth</option><option>Premium</option><option>Individuell</option></select><select className="input" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Offen</option><option>Angenommen</option><option>Beauftragt</option><option>Gewonnen</option><option>Abgelehnt</option></select><button className="btn" onClick={save}>Speichern</button></Card><Card title="Angebote">{items.map(i=><div className="item" key={i.id}>{i.offer_number} · {i.title}<br/>{money(i.amount)}<select className="input" value={i.status} onChange={e=>update(i,e.target.value)}><option>Offen</option><option>Angenommen</option><option>Beauftragt</option><option>Gewonnen</option><option>Abgelehnt</option></select></div>)}</Card></div>}
function Contracts({customer}:any){const[items,setItems]=useState<any[]>([]),[form,setForm]=useState({contract_name:'',package_name:'Growth',monthly_value:499,start_date:today(),status:'Aktiv'});useEffect(()=>{load()},[customer]);async function load(){const{data}=await supabase.from('contracts').select('*').eq('customer_id',customer.id);setItems(data||[])}async function save(){await supabase.from('contracts').insert({customer_id:customer.id,...form});load()}return <div className="grid2"><Card title="Vertrag"><input className="input" placeholder="Name" value={form.contract_name} onChange={e=>setForm({...form,contract_name:e.target.value})}/><input className="input" type="number" value={form.monthly_value} onChange={e=>setForm({...form,monthly_value:Number(e.target.value)})}/><button className="btn" onClick={save}>Speichern</button></Card><Card title="Verträge">{items.map(i=><div className="item" key={i.id}>{i.contract_name}<br/>{money(i.monthly_value)} · {i.status}</div>)}</Card></div>}

function OnboardingAdmin({customers}:any){const[items,setItems]=useState<any[]>([]);useEffect(()=>{load()},[]);async function load(){const{data}=await supabase.from('package_requests').select('*,customers(*)').order('created_at',{ascending:false});setItems(data||[])}async function approve(i:any){const res=await fetch(API+'/api/onboarding/approve-package',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer_id:i.customer_id,package_name:i.package_name})});const d=await res.json();if(!res.ok)alert(d.error);else alert('Freigeschaltet');load()}return <><Hero title="Onboarding Center" text="Registrierungen, Paketanfragen, Vertragsflow und Toolfreigabe."/><Card title="Paketanfragen">{items.map(i=><div className="item" key={i.id}><b>{i.customers?.name}</b><br/>{i.package_name} · {i.status}<br/><button className="btn" onClick={()=>approve(i)}>Freischalten + Vertrag erzeugen</button></div>)}</Card></>}

function Finance({customers,customer}:any){const[items,setItems]=useState<any[]>([]),[form,setForm]=useState({customer_id:customer?.id||'',amount:0,service:''});useEffect(()=>{load()},[customer]);async function load(){let q=supabase.from('invoices').select('*,customers(*)').order('created_at',{ascending:false});if(customer)q=q.eq('customer_id',customer.id);const{data}=await q;setItems(data||[])}async function save(){const cid=form.customer_id||customer?.id;if(!cid)return alert('Kunde wählen');await supabase.from('invoices').insert({invoice_number:'RE-'+Date.now(),customer_id:cid,amount:form.amount,service:form.service,due_date:plus14(),status:'Offen'});load()}async function status(i:any,s:string){await supabase.from('invoices').update({status:s,paid_at:s==='Bezahlt'?new Date().toISOString():null}).eq('id',i.id);if(s==='Überfällig')await supabase.from('reminders').insert({invoice_id:i.id,customer_id:i.customer_id,reminder_number:'MA-'+Date.now(),level:'1. Mahnung'});load()}return <><Hero title="Finance Suite" text="Rechnungen, Mahnungen und Verträge."/><div className="grid2"><Card title="Rechnung erstellen">{!customer&&<select className="input" value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value})}><option value="">Kunde wählen</option>{customers.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select>}<input className="input" type="number" value={form.amount} onChange={e=>setForm({...form,amount:Number(e.target.value)})}/><input className="input" placeholder="Leistung" value={form.service} onChange={e=>setForm({...form,service:e.target.value})}/><button className="btn" onClick={save}>Speichern</button></Card><Card title="Rechnungen"><div className="scroll">{items.map(i=><div className="item" key={i.id}>{i.invoice_number} · {i.customers?.name}<br/>{money(i.amount)}<select className="input" value={i.status} onChange={e=>status(i,e.target.value)}><option>Offen</option><option>Bezahlt</option><option>Überfällig</option></select><button className="btn secondary" onClick={async()=>{const r=await fetch(API+'/api/pdf/invoice/'+i.id,{method:'POST'});const d=await r.json();if(d.url)window.open(d.url,'_blank')}}>PDF erzeugen</button>{i.file_url&&<button className="btn secondary" onClick={()=>window.open(i.file_url,'_blank')}>Download</button>}</div>)}</div></Card></div></>}
function SEOControl({customers,customer}:any){const[cid,setCid]=useState(customer?.id||''),[form,setForm]=useState<any>({month:'Aktuell',organic_traffic:0,impressions:0,clicks:0,ctr:0,avg_position:0,top10_keywords:0,backlinks:0,technical_score:0,local_visibility:0});async function save(){const customer_id=cid||customer?.id;if(!customer_id)return alert('Kunde wählen');await supabase.from('seo_traffic').insert({...form,customer_id});alert('Gespeichert')}async function sync(){const customer_id=cid||customer?.id;if(!customer_id)return alert('Kunde wählen');const res=await fetch(API+'/api/google-business/mock-sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer_id})});alert(res.ok?'Demo Sync ausgeführt':'Fehler')}return <><Hero title="SEO Control Center" text="SEO Master Control und Google Business Demo Sync."/><Card title="SEO Werte">{!customer&&<select className="input" value={cid} onChange={e=>setCid(e.target.value)}><option value="">Kunde wählen</option>{customers.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select>}<div className="grid4">{Object.keys(form).map(k=><input key={k} className="input" type={k==='month'?'text':'number'} placeholder={k} value={form[k]} onChange={e=>setForm({...form,[k]:k==='month'?e.target.value:Number(e.target.value)})}/>)}</div><button className="btn" onClick={save}>Speichern</button><button className="btn secondary" onClick={sync}>Google Business Demo Sync</button></Card></>}
function Pipeline({customers}:any){const[items,setItems]=useState<any[]>([]),[form,setForm]=useState({customer_id:'',deal_name:'',stage:'Lead',value:0,probability:25});useEffect(()=>{load()},[]);async function load(){const{data}=await supabase.from('sales_pipeline').select('*,customers(*)').order('created_at',{ascending:false});setItems(data||[])}async function save(){await supabase.from('sales_pipeline').insert(form);load()}return <><Hero title="Sales Pipeline" text="Deals, Forecasts und Abschlusswahrscheinlichkeiten."/><div className="grid2"><Card title="Deal"><select className="input" value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value})}><option value="">Kunde</option>{customers.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input className="input" placeholder="Deal" value={form.deal_name} onChange={e=>setForm({...form,deal_name:e.target.value})}/><input className="input" type="number" value={form.value} onChange={e=>setForm({...form,value:Number(e.target.value)})}/><button className="btn" onClick={save}>Speichern</button></Card><Card title="Deals">{items.map(i=><div className="item" key={i.id}>{i.deal_name}<br/>{i.customers?.name} · {money(i.value)} · {i.probability}%</div>)}</Card></div></>}
function Operations({customer}:any){const[items,setItems]=useState<any[]>([]);useEffect(()=>{load()},[customer]);async function load(){let q=supabase.from('tickets').select('*,customers(*)').order('created_at',{ascending:false});if(customer)q=q.eq('customer_id',customer.id);const{data}=await q;setItems(data||[])}async function upd(id:string,status:string){await supabase.from('tickets').update({status}).eq('id',id);load()}return <><Hero title="Operations Center" text="Tickets, Support, Prioritäten und Bearbeitung."/><Card title="Tickets">{items.map(i=><div className="item" key={i.id}>{i.customers?.name}<br/><b>{i.title}</b><p>{i.description}</p><select className="input" value={i.status} onChange={e=>upd(i.id,e.target.value)}><option>angekommen</option><option>in Bearbeitung</option><option>erledigt</option></select></div>)}</Card></>}
function Automations(){const[items,setItems]=useState<any[]>([]);useEffect(()=>{supabase.from('automation_rules').select('*').then(({data})=>setItems(data||[]))},[]);return <><Hero title="Automation Center" text="Workflow Engine: Wenn X passiert, dann Y."/><Card title="Regeln">{items.map(i=><div className="item" key={i.id}>{i.name}<br/>{i.trigger_type} → {i.action_type}</div>)}</Card></>}
function Notifications(){const[items,setItems]=useState<any[]>([]);useEffect(()=>{supabase.from('notifications').select('*,customers(*)').order('created_at',{ascending:false}).limit(80).then(({data})=>setItems(data||[]))},[]);return <><Hero title="Notification Center" text="Alle Systemmeldungen und Kundenereignisse."/><Card title="Meldungen">{items.map(i=><div className="item" key={i.id}><b>{i.title}</b><br/>{i.customers?.name}<p>{i.message}</p></div>)}</Card></>}
function GlobalSearch(){const[q,setQ]=useState(''),[results,setResults]=useState<any[]>([]);async function search(){const res=await fetch(API+'/api/search/global?q='+encodeURIComponent(q));const data=await res.json();setResults(data.results||[])}return <><Hero title="Global Search" text="Suche über Kunden, Rechnungen, Tickets und Angebote."/><Card title="Suche"><input className="input" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')search()}}/><button className="btn" onClick={search}>Suchen</button></Card><Card title="Ergebnisse">{results.map((r,i)=><div className="item" key={i}>{r.type}: {r.title}<br/>{r.subtitle}</div>)}</Card></>}
function ThemeCenter({theme,setTheme}:any){return <><Hero title="Design System" text="Purple Premium und Executive Professional."/><Card title="Theme"><button className={theme==='purple'?'btn':'btn secondary'} onClick={()=>setTheme('purple')}>Purple Premium</button><button className={theme==='executive'?'btn':'btn secondary'} onClick={()=>setTheme('executive')}>Executive Professional</button></Card></>}
function Audit(){return <><Hero title="Audit Center" text="Audit-ready Struktur. Logs werden über activity_logs und audit_logs vorbereitet."/><Card title="Status">Audit Layer vorbereitet.</Card></>}

function CustomerDashboard({customer}:any){return <><Hero title={`Willkommen, ${customer?.name||'Kunde'}`} text="Kundenportal mit freigeschalteten Tools."/><div className="grid4"><Card title="Bewertung"><div className="kpi">{customer?.rating||0}★</div></Card><Card title="Status"><div className="kpi">{customer?.status||'Aktiv'}</div></Card><Card title="Health"><div className="kpi healthGreen">🟢</div></Card><Card title="Tools"><div className="kpi">aktiv</div></Card></div></>}
function CustomerSEO({customer}:any){const[traffic,setTraffic]=useState<any[]>([]),[keywords,setKeywords]=useState<any[]>([]);useEffect(()=>{if(customer){supabase.from('seo_traffic').select('*').eq('customer_id',customer.id).order('created_at',{ascending:true}).then(({data})=>setTraffic(data||[]));supabase.from('seo_keywords').select('*').eq('customer_id',customer.id).then(({data})=>setKeywords(data||[]))}},[customer]);const latest=traffic[traffic.length-1]||{};return <><Hero title="SEO Suite" text="Live SEO KPIs, Keywords und Trends."/><div className="grid4"><Card title="Traffic"><div className="kpi">{latest.organic_traffic||0}</div></Card><Card title="Impressionen"><div className="kpi">{latest.impressions||0}</div></Card><Card title="CTR"><div className="kpi">{latest.ctr||0}%</div></Card><Card title="Top10"><div className="kpi">{latest.top10_keywords||0}</div></Card></div><Card title="Keywords">{keywords.map(k=><div className="item" key={k.id}>{k.keyword}<br/>Position {k.position}</div>)}</Card></>}
function Booking({customer}:any){const[items,setItems]=useState<any[]>([]),[week,setWeek]=useState(0),[open,setOpen]=useState(false),[form,setForm]=useState({client_name:'',appointment_date:today(),start_time:'09:00',end_time:'10:00',notes:''});useEffect(()=>{load()},[customer]);async function load(){const{data}=await supabase.from('appointments').select('*').eq('customer_id',customer.id).order('appointment_date',{ascending:true});setItems(data||[])}async function save(){await supabase.from('appointments').insert({...form,customer_id:customer.id});setOpen(false);load()}const days=weekDays(week),hours=Array.from({length:15},(_,i)=>String(i+7).padStart(2,'0')+':00');return <><Hero title="Booking Center" text="Wochenkalender mit Endzeiten."/><button className="btn" onClick={()=>setOpen(true)}>Termin erstellen</button><div className="row"><button className="btn secondary" onClick={()=>setWeek(week-1)}>← Vorwoche</button><button className="btn secondary" onClick={()=>setWeek(0)}>Heute</button><button className="btn secondary" onClick={()=>setWeek(week+1)}>Nächste Woche →</button></div><div style={{overflow:'auto'}}><div className="calendar"><div>Zeit</div>{days.map(d=><div className="calHead" key={d.iso}>{d.label}</div>)}{hours.map(h=><><div className="calTime">{h}</div>{days.map(d=><div className="calCell" key={d.iso+h}>{items.filter(i=>i.appointment_date===d.iso&&(i.start_time||'').slice(0,2)===h.slice(0,2)).map(i=><button className="calEvent" key={i.id}>{i.client_name}<br/>{i.start_time}-{i.end_time}</button>)}</div>)}</>)}</div></div>{open&&<Modal title="Termin" onClose={()=>setOpen(false)}><input className="input" placeholder="Name" value={form.client_name} onChange={e=>setForm({...form,client_name:e.target.value})}/><input className="input" type="date" value={form.appointment_date} onChange={e=>setForm({...form,appointment_date:e.target.value})}/><input className="input" value={form.start_time} onChange={e=>setForm({...form,start_time:e.target.value})}/><input className="input" value={form.end_time} onChange={e=>setForm({...form,end_time:e.target.value})}/><button className="btn" onClick={save}>Speichern</button></Modal>}</>}
function CustomerTickets({customer,profile}:any){const[items,setItems]=useState<any[]>([]),[form,setForm]=useState({title:'',description:'',priority:'Normal'});useEffect(()=>{load()},[customer]);async function load(){const{data}=await supabase.from('tickets').select('*').eq('customer_id',customer.id).order('created_at',{ascending:false}).limit(12);setItems(data||[])}async function save(){await supabase.from('tickets').insert({...form,customer_id:customer.id,created_by:profile.id});setForm({title:'',description:'',priority:'Normal'});load()}return <><Hero title="Support Center" text="Ticketsystem mit Prioritäten."/><div className="grid2"><Card title="Ticket erstellen"><input className="input" placeholder="Titel" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea className="input" placeholder="Beschreibung" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><select className="input" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>Normal</option><option>Dringend</option></select><button className="btn" onClick={save}>Senden</button></Card><Card title="Tickets">{items.map(i=><div className="item" key={i.id}>{i.title}<br/>{i.status} · {i.priority}</div>)}</Card></div></>}
function CustomerFinance({customer}:any){const[items,setItems]=useState<any[]>([]);useEffect(()=>{supabase.from('invoices').select('*').eq('customer_id',customer.id).order('created_at',{ascending:false}).then(({data})=>setItems(data||[]))},[customer]);return <><Hero title="Finance Center" text="Rechnungen und Mahnungen."/><Card title="Rechnungen">{items.map(i=><div className="item" key={i.id}>{i.invoice_number}<br/>{money(i.amount)} · {i.status}<br/>{i.file_url&&<button className="btn secondary" onClick={()=>window.open(i.file_url,'_blank')}>PDF Download</button>}</div>)}</Card></>}
function Goals({customer}:any){const[items,setItems]=useState<any[]>([]),[form,setForm]=useState({goal_name:'',metric:'rating',target_value:0,start_date:today(),end_date:today()});useEffect(()=>{load()},[customer]);async function load(){const{data}=await supabase.from('customer_goals').select('*').eq('customer_id',customer.id);setItems(data||[])}async function save(){await supabase.from('customer_goals').insert({...form,customer_id:customer.id,current_value:0});load()}return <><Hero title="Zielsystem" text="KPI Ziele und Fortschritt."/><div className="grid2"><Card title="Ziel"><input className="input" placeholder="Zielname" value={form.goal_name} onChange={e=>setForm({...form,goal_name:e.target.value})}/><select className="input" value={form.metric} onChange={e=>setForm({...form,metric:e.target.value})}><option value="rating">Ø Bewertung</option><option value="organic_traffic">SEO Traffic</option><option value="impressions">Impressionen</option><option value="ctr">CTR</option></select><input className="input" type="number" value={form.target_value} onChange={e=>setForm({...form,target_value:Number(e.target.value)})}/><button className="btn" onClick={save}>Speichern</button></Card><Card title="Ziele">{items.map(i=><div className="item" key={i.id}>{i.goal_name}<br/>{i.current_value}/{i.target_value}</div>)}</Card></div></>}
function Growth({customer}:any){const[items,setItems]=useState<any[]>([]),[form,setForm]=useState({reviewer_name:'',rating:5,review_text:''});useEffect(()=>{if(customer)supabase.from('review_ai_replies').select('*').eq('customer_id',customer.id).order('created_at',{ascending:false}).then(({data})=>setItems(data||[]))},[customer]);function gen(){const bad=['idiot','scheiße','arsch','dreck','abzocke'].some(w=>form.review_text.toLowerCase().includes(w));return (bad?'Hinweis: beleidigende Sprache erkannt. ':'')+(Number(form.rating)>=4?'Vielen Dank für die tolle Bewertung!':'Vielen Dank für Ihr Feedback. Wir möchten den Fall gern klären.')}async function save(){await supabase.from('review_ai_replies').insert({...form,customer_id:customer.id,suggested_reply:gen(),bad_words_detected:gen().includes('Hinweis')});const{data}=await supabase.from('review_ai_replies').select('*').eq('customer_id',customer.id).order('created_at',{ascending:false});setItems(data||[])}return <><Hero title="Growth Center" text="Review KI, QR und Reports."/><div className="grid2"><Card title="Review KI"><input className="input" placeholder="Name" value={form.reviewer_name} onChange={e=>setForm({...form,reviewer_name:e.target.value})}/><select className="input" value={form.rating} onChange={e=>setForm({...form,rating:Number(e.target.value)})}><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option></select><textarea className="input" value={form.review_text} onChange={e=>setForm({...form,review_text:e.target.value})}/><button className="btn" onClick={save}>Antwort generieren</button></Card><Card title="Antworten"><div className="scroll">{items.map(i=><div className="item" key={i.id}>{i.reviewer_name} · {i.rating}★<br/>{i.suggested_reply}</div>)}</div></Card></div></>}
function Integrations({customer}:any){const[items,setItems]=useState<any[]>([]),[form,setForm]=useState({platform:'Google Business',account_id:'',location_id:'',connected_email:''});useEffect(()=>{load()},[customer]);async function load(){const{data}=await supabase.from('integrations').select('*').eq('customer_id',customer.id);setItems(data||[])}async function save(){await supabase.from('integrations').insert({...form,customer_id:customer.id});load()}return <><Hero title="Integrationen" text="API Keys und Google Business Vorbereitung."/><div className="grid2"><Card title="Integration"><input className="input" value={form.platform} onChange={e=>setForm({...form,platform:e.target.value})}/><input className="input" placeholder="Account ID" value={form.account_id} onChange={e=>setForm({...form,account_id:e.target.value})}/><input className="input" placeholder="Location ID" value={form.location_id} onChange={e=>setForm({...form,location_id:e.target.value})}/><input className="input" placeholder="E-Mail" value={form.connected_email} onChange={e=>setForm({...form,connected_email:e.target.value})}/><button className="btn" onClick={save}>Speichern</button></Card><Card title="Verbunden">{items.map(i=><div className="item" key={i.id}>{i.platform}<br/>{i.connected_email}</div>)}</Card></div></>}
function Locations({customer}:any){const[items,setItems]=useState<any[]>([]);useEffect(()=>{supabase.from('multi_locations').select('*').eq('customer_id',customer.id).eq('enabled',true).then(({data})=>setItems(data||[]))},[customer]);return <><Hero title="Standorte" text="Multi Standortverwaltung."/><Card title="Standorte">{items.map(i=><div className="item" key={i.id}>{i.location_name}<br/>{i.address}</div>)}</Card></>}
function Templates(){return <><Hero title="E-Mail Vorlagen" text="Vorlagenmodul vorbereitet."/><Card title="Vorlagen">Vorlagen werden über Admin Templates gepflegt.</Card></>}


// ===== MMOS IMPERSONATION FEATURE =====
export function ImpersonationInfo(){
  return null
}
