
'use client'

import { useEffect, useMemo, useState } from 'react'
import { Area, AreaChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { supabase, hasSupabase } from '@/lib/supabase'

type Role='guest'|'admin'|'customer'
const uid=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2)
const eur=(v:any)=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(v||0))
const ids={barber:'11111111-1111-1111-1111-111111111111',roof:'22222222-2222-2222-2222-222222222222',restaurant:'33333333-3333-3333-3333-333333333333',fitness:'44444444-4444-4444-4444-444444444444'}
const packages:any={Starter:{price:199,tools:['CRM','Tickets','Rechnungen','Media Center']},Growth:{price:499,tools:['GBP','SEO','Review Funnel','Booking','Monatsreport','Smart Widgets']},Premium:{price:899,tools:['AI Antworten','Heatmap Karte','Command Palette','Automationen','Success Score']}}

const seed:any={
 customers:[
  {id:ids.barber,name:'Barber Lounge Rostock',branch:'Friseur',email:'kontakt@barber-lounge-rostock.de',phone:'0381 123456',address:'Kröpeliner Str. 12',zip:'18055',city:'Rostock',status:'Aktiv',package_name:'Growth',google_review_url:'https://g.page/r/demo-barber/review'},
  {id:ids.roof,name:'NordDach GmbH',branch:'Dachdecker',email:'kontakt@norddach.de',phone:'0385 987654',address:'Wismarsche Str. 88',zip:'19053',city:'Schwerin',status:'Aktiv',package_name:'Premium',google_review_url:'https://g.page/r/demo-dach/review'},
  {id:ids.restaurant,name:'Alexas Inselblick',branch:'Restaurant',email:'kontakt@alexas-inselblick.de',phone:'03991 123456',address:'Am See 4',zip:'17192',city:'Waren',status:'Aktiv',package_name:'Growth',google_review_url:'https://g.page/r/demo-restaurant/review'},
  {id:ids.fitness,name:'Baltic Fitness Club',branch:'Fitnessstudio',email:'kontakt@baltic-fitness.de',phone:'03834 567890',address:'Markt 7',zip:'17489',city:'Greifswald',status:'Aktiv',package_name:'Premium',google_review_url:'https://g.page/r/demo-fitness/review'}
 ],
 invoices:[{id:'i1',customer_id:ids.barber,invoice_number:'RE-BAR-001',service_type:'Growth Paketgebühr',amount:499,status:'Bezahlt',created_at:'2026-05-01'}],
 recurring_billing_rules:[{id:'rb1',customer_id:ids.barber,package_name:'Growth',amount:499,interval:'monthly',next_run:'2026-06-01',enabled:true}],
 appointments:[{id:'a1',customer_id:ids.barber,client_name:'Strategie Call',appointment_date:'2026-05-15',start_time:'10:00',end_time:'11:00',status:'Geplant',review_funnel_enabled:true}],
 seo_snapshots:[{id:'s1',customer_id:ids.barber,organic_traffic:3200,impressions:42000,clicks:1450,ctr:3.45,top10_keywords:18,visibility_score:72,created_at:'2026-05-01'}],
 google_business_profiles:[{id:'gbp1',customer_id:ids.barber,rating:4.8,reviews_count:186,local_rank:3,profile_score:86,calls:42,directions:31,website_clicks:58,photo_views:1240,status:'Verbunden'}],
 reviews:[{id:'rv1',customer_id:ids.barber,author:'Max M.',rating:5,text:'Super Haarschnitt.',status:'Öffentlich',created_at:'2026-05-01'},{id:'rv2',customer_id:ids.barber,author:'Anonym',rating:2,text:'Lange Wartezeit.',status:'Internes Feedback',created_at:'2026-05-04'}],
 review_keywords:[{id:'kw1',customer_id:ids.barber,keyword:'Wartezeit',reply_template:'Danke für Ihr Feedback. Wir prüfen intern unsere Terminplanung.'}],
 qr_campaigns:[{id:'qr1',customer_id:ids.barber,title:'Bewertungs QR Barber',internal_from:1,internal_to:3,google_from:4,google_to:5,internal_email:'feedback@barber-lounge.de',google_review_url:'https://g.page/r/demo-barber/review',status:'Aktiv'}],
 media_assets:[{id:'ma1',customer_id:ids.barber,name:'Logo Barber Lounge.png',asset_type:'Logo',url:'#',version:1}],
 file_versions:[{id:'fv1',customer_id:ids.barber,asset_id:'ma1',version:1,name:'Logo Barber Lounge.png',url:'#'}],
 local_seo_heatmap:[{id:'hm1',customer_id:ids.barber,keyword:'barber rostock',area:'Innenstadt',rank:3,lat:54.089,lon:12.132},{id:'hm2',customer_id:ids.barber,keyword:'herrenfriseur rostock',area:'Kröpeliner Tor',rank:5,lat:54.092,lon:12.122},{id:'hm3',customer_id:ids.barber,keyword:'bart schneiden rostock',area:'Warnemünde',rank:8,lat:54.176,lon:12.087}],
 package_requests:[], customer_subscriptions:[{id:'sub1',customer_id:ids.barber,package_name:'Growth',status:'active',price_monthly:499}],
 notifications:[{id:'n1',customer_id:ids.barber,title:'Review Funnel',message:'Termin-Review-Funnel ist aktiv.',priority:'Normal',created_at:'2026-05-04'}],
 activity_logs:[{id:'al1',customer_id:ids.barber,action:'media_uploaded',message:'Logo hochgeladen',created_at:'2026-05-01'}],
 dashboard_widgets:[
  {id:'w1',customer_id:ids.barber,key:'success_score',title:'Client Success Score',enabled:true,order_index:1},
  {id:'w2',customer_id:ids.barber,key:'reviews',title:'Bewertungen',enabled:true,order_index:2},
  {id:'w3',customer_id:ids.barber,key:'heatmap',title:'SEO Heatmap',enabled:true,order_index:3}
 ],
 tickets:[], ticket_messages:[], monthly_reports:[], report_templates:[], landing_pages:[], integrations:[], automations:[], workflow_runs:[]
}

function useStore(){
 const [data,setData]=useState<any>(seed); const [toast,setToast]=useState('')
 const tables=['customers','invoices','recurring_billing_rules','appointments','seo_snapshots','google_business_profiles','reviews','review_keywords','qr_campaigns','media_assets','file_versions','local_seo_heatmap','package_requests','customer_subscriptions','notifications','activity_logs','dashboard_widgets','tickets','ticket_messages','monthly_reports','report_templates','landing_pages','integrations','automations','workflow_runs']
 function notify(m:string){setToast(m);setTimeout(()=>setToast(''),2400)}
 async function load(){if(!hasSupabase||!supabase)return;const r:any={};for(const t of tables){const {data}=await supabase.from(t).select('*');r[t]=data||[]}setData((p:any)=>({...p,...r}))}
 useEffect(()=>{load()},[])
 async function create(table:string,row:any){try{const payload={...row,created_at:row.created_at||new Date().toISOString()};if(hasSupabase&&supabase){const {error}=await supabase.from(table).insert(payload);if(error)throw error;await load()}else setData((p:any)=>({...p,[table]:[{...payload,id:uid()},...(p[table]||[])]}));notify('Gespeichert')}catch(e:any){alert(e.message||'Fehler')}}
 async function update(table:string,id:string,row:any){try{if(hasSupabase&&supabase){const {error}=await supabase.from(table).update(row).eq('id',id);if(error)throw error;await load()}else setData((p:any)=>({...p,[table]:(p[table]||[]).map((x:any)=>x.id===id?{...x,...row}:x)}));notify('Aktualisiert')}catch(e:any){alert(e.message||'Fehler')}}
 return {data,setData,create,update,load,toast}
}
function cname(d:any,id:string){return d.customers.find((c:any)=>c.id===id)?.name||'Kunde'}
function cpkg(d:any,id:string){return d.customer_subscriptions.find((s:any)=>s.customer_id===id)?.package_name||d.customers.find((c:any)=>c.id===id)?.package_name||'Starter'}
function successScore(d:any,id:string){const g=d.google_business_profiles.find((x:any)=>x.customer_id===id)||{};const seo=d.seo_snapshots.find((x:any)=>x.customer_id===id)||{};const open=d.tickets.filter((t:any)=>t.customer_id===id&&t.status!=='Geschlossen').length;return Math.max(0,Math.min(100,Math.round((g.profile_score||50)*.35+(g.rating||4)*10+(seo.visibility_score||50)*.25-open*3)))}
function Toast({m}:any){return m?<div className="toast green">{m}</div>:null}
function Badge({children,type='purple'}:any){return <span className={`badge ${type}`}>{children}</span>}
function Card({title,children,action}:any){return <section className="card"><div className="row between"><h2>{title}</h2>{action}</div>{children}</section>}
function Head({title,sub,action}:any){return <div className="head"><div><h1>{title}</h1>{sub&&<div className="sub">{sub}</div>}</div>{action}</div>}
function Metric({label,value,sub}:any){return <div className="metric"><div className="metricLabel">{label}</div><div className="metricValue">{value}</div>{sub&&<div className="delta">{sub}</div>}</div>}
function Search({items,value,onChange,placeholder}:any){const [q,setQ]=useState('');const s=items.find((x:any)=>x.id===value);const list=items.filter((x:any)=>(x.name+x.branch+x.email).toLowerCase().includes(q.toLowerCase()));return <div style={{position:'relative'}}><input className="input" placeholder={placeholder} value={s&&!q?s.name:q} onChange={e=>{setQ(e.target.value);if(s)onChange('')}}/>{q&&<div className="card" style={{position:'absolute',zIndex:50,width:'100%',padding:6,maxHeight:220,overflow:'auto'}}>{list.map((x:any)=><button className="nav" key={x.id} onClick={()=>{onChange(x.id);setQ('')}}>{x.name}<div className="sub">{x.branch} · {x.package_name}</div></button>)}</div>}</div>}
function SEOChart({rows}:any){return <div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={rows}><CartesianGrid stroke="#1e293b"/><XAxis dataKey="label" stroke="#8b9bb3"/><YAxis stroke="#8b9bb3"/><Tooltip contentStyle={{background:'#0d1420',border:'1px solid #243044',color:'#fff'}}/><Legend/><Area dataKey="traffic" name="Traffic" stroke="#38bdf8" fill="#38bdf844"/><Area dataKey="impressions" name="Impressionen" stroke="#7c3aed" fill="#7c3aed33"/><Area dataKey="keywords" name="Top10 Keywords" stroke="#22c55e" fill="#22c55e22"/></AreaChart></ResponsiveContainer></div>}

export default function App(){
 const store=useStore(); const [role,setRole]=useState<Role>('guest'); const [view,setView]=useState('dashboard'); const [cid,setCid]=useState(ids.barber); const [cmd,setCmd]=useState(false); const [light,setLight]=useState(false); const [notif,setNotif]=useState(false)
 useEffect(()=>{document.body.classList.toggle('light-mode',light)},[light])
 useEffect(()=>{const h=(e:any)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setCmd(true)}};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[])
 const admin=['dashboard','crm','gbp','reviews','reports','media','landing_builder','heatmap','tickets','booking','billing','packages','notifications']
 const customer=['dashboard','seo','reviews','booking','media','packages','notifications']
 const labels:any={dashboard:'Dashboard',crm:'CRM',gbp:'Google Business',reviews:'Reviews & QR',reports:'Monatsreports',media:'Media Center',landing_builder:'Landingpages',heatmap:'SEO Heatmap',tickets:'Tickets',booking:'Booking',billing:'Rechnungsläufe',packages:'Pakete',notifications:'Notifications',seo:'SEO'}
 if(role==='guest')return <div className="landing"><div className="landingNav"><div className="logo"><div className="mark">M</div>MMOS v20</div><div className="row"><button className="btn" onClick={()=>setRole('admin')}>Demo Admin</button><button className="btn secondary" onClick={()=>setRole('customer')}>Demo Kunde</button></div></div><section className="hero"><h1>Workflow-ready Marketing OS</h1><p>Storage, Review Automation, Rechnungsjobs, Command Palette, Timeline, Widgets und Heatmap-Karte.</p></section><div className="grid3">{Object.entries(packages).map(([p,v]:any)=><Card key={p} title={p}><div className="metricValue">{eur(v.price)}</div>{v.tools.map((t:string)=><div className="item" key={t}><span>{t}</span><Badge type="green">inkl.</Badge></div>)}</Card>)}</div></div>
 const nav=role==='admin'?admin:customer
 return <div className="app"><aside className="side"><div className="logo"><div className="mark">M</div>MMOS</div>{role==='admin'&&<Search items={store.data.customers} value={cid} onChange={setCid} placeholder="Kundensuche"/>}{nav.map(k=><button key={k} className={`nav ${view===k?'active':''}`} onClick={()=>setView(k)}>{labels[k]}</button>)}<button className="nav" onClick={()=>setRole('guest')}>Logout</button></aside><main className="main"><div className="top"><input className="search" placeholder="Suche... CMD+K" onFocus={()=>setCmd(true)}/><button className="btn secondary" onClick={()=>setLight(!light)}>{light?'Dark':'Light'}</button><button className="btn secondary" onClick={()=>setNotif(true)}>🔔 {store.data.notifications.length}</button><Badge>{role==='admin'?'Admintool':'Kundenportal'} · {role==='customer'?cname(store.data,cid):'Global'}</Badge></div><Toast m={store.toast}/>
 {cmd&&<CommandPalette store={store} setView={setView} setCid={setCid} close={()=>setCmd(false)}/>}
 {notif&&<NotificationCenter store={store} cid={cid} role={role} close={()=>setNotif(false)}/>}
 {view==='dashboard'&&<Dashboard store={store} cid={cid} role={role}/>}
 {view==='crm'&&role==='admin'&&<CRM store={store} cid={cid}/>}
 {view==='gbp'&&role==='admin'&&<GoogleBusiness store={store} cid={cid}/>}
 {view==='seo'&&role==='customer'&&<CustomerSEO store={store} cid={cid}/>}
 {view==='reviews'&&<ReviewsQR store={store} cid={cid} role={role}/>}
 {view==='reports'&&role==='admin'&&<Reports store={store} cid={cid}/>}
 {view==='media'&&<MediaCenter store={store} cid={cid} role={role}/>}
 {view==='landing_builder'&&role==='admin'&&<LandingBuilder store={store} cid={cid}/>}
 {view==='heatmap'&&role==='admin'&&<Heatmap store={store} cid={cid}/>}
 {view==='tickets'&&role==='admin'&&<Tickets/>}
 {view==='booking'&&<Booking store={store} cid={cid} role={role}/>}
 {view==='billing'&&role==='admin'&&<BillingRuns store={store} cid={cid}/>}
 {view==='packages'&&<Packages store={store} cid={cid} role={role}/>}
 {view==='notifications'&&<Notifications store={store} cid={cid} role={role}/>}
 </main></div>
}
function CommandPalette({store,setView,setCid,close}:any){const actions=[['Dashboard','dashboard'],['CRM','crm'],['Media Center','media'],['SEO Heatmap','heatmap'],['Rechnungsläufe','billing'],['Booking','booking']];return <div className="modal"><div className="card modalCard"><Head title="Command Palette" sub="Schnellzugriff mit CMD/CTRL+K"/>{actions.map(([label,v]:any)=><button key={v} className="nav" onClick={()=>{setView(v);close()}}>Öffne {label}</button>)}<div className="sub">Kunden direkt öffnen</div>{store.data.customers.map((c:any)=><button className="nav" key={c.id} onClick={()=>{setCid(c.id);setView('crm');close()}}>{c.name}</button>)}<button className="btn secondary" onClick={close}>Schließen</button></div></div>}
function NotificationCenter({store,cid,role,close}:any){const rows=store.data.notifications.filter((n:any)=>role==='admin'||n.customer_id===cid);return <div className="modal"><div className="card modalCard"><Head title="Notification Center" action={<button className="btn secondary" onClick={close}>Schließen</button>}/>{rows.map((n:any)=><div className="item" key={n.id}><div><b>{n.title}</b><div className="sub">{n.message}</div></div><Badge>{n.priority||'Info'}</Badge></div>)}</div></div>}
function Dashboard({store,cid,role}:any){const score=successScore(store.data,cid);const gbp=store.data.google_business_profiles.find((x:any)=>x.customer_id===cid)||{};const widgets=store.data.dashboard_widgets.filter((w:any)=>w.customer_id===cid&&w.enabled).sort((a:any,b:any)=>a.order_index-b.order_index);return <><Head title={role==='admin'?'Admin Dashboard':'Kunden Dashboard'} sub="Smart Widgets, Notifications und Success Score."/><div className="grid4"><Metric label="Client Success Score" value={`${score}/100`} sub={score>80?'Stark':'Optimierung möglich'}/><Metric label="GBP Rating" value={gbp.rating||0}/><Metric label="Anrufe" value={gbp.calls||0}/><Metric label="Widgets" value={widgets.length}/></div><Card title="Smart Dashboard Widgets">{widgets.map((w:any)=><div className="item" key={w.id}><b>{w.title}</b><button className="btn secondary" onClick={()=>store.update('dashboard_widgets',w.id,{enabled:false})}>Ausblenden</button></div>)}</Card></>}
function CRM({store,cid}:any){return <><Head title="CRM Detail" sub={cname(store.data,cid)}/><QuickActions store={store} cid={cid}/><div className="grid2"><ClientTimeline store={store} cid={cid}/><GoogleBusiness store={store} cid={cid} compact/></div><MediaCenter store={store} cid={cid} role="admin" compact/></>}
function QuickActions({store,cid}:any){return <Card title="Smart Quick Actions"><div className="row wrap"><button className="btn secondary" onClick={()=>store.create('invoices',{customer_id:cid,invoice_number:'RE-'+Date.now(),service_type:'Quick Invoice',amount:199,status:'Offen'})}>Rechnung erstellen</button><button className="btn secondary" onClick={()=>store.create('notifications',{customer_id:cid,title:'Review Funnel',message:'Review Funnel vorbereitet'})}>Review Funnel senden</button><button className="btn secondary" onClick={()=>store.create('monthly_reports',{customer_id:cid,title:'Quick Monatsreport',status:'Entwurf'})}>Monatsreport erzeugen</button><button className="btn secondary" onClick={()=>store.create('media_assets',{customer_id:cid,name:'Neues Asset',asset_type:'Notiz',url:'#'})}>Asset anlegen</button></div></Card>}
function ClientTimeline({store,cid}:any){const rows=[...store.data.activity_logs.filter((x:any)=>x.customer_id===cid),...store.data.notifications.filter((x:any)=>x.customer_id===cid).map((n:any)=>({...n,action:'notification',message:n.title+' - '+n.message}))].sort((a:any,b:any)=>String(b.created_at).localeCompare(String(a.created_at)));return <Card title="Universal Activity Timeline">{rows.map((r:any)=><div className="item" key={r.id}><b>{r.action}</b><span>{r.message}</span></div>)}</Card>}
function GoogleBusiness({store,cid,compact=false}:any){const g=store.data.google_business_profiles.find((x:any)=>x.customer_id===cid)||{};return <><Head title={compact?'Google Business':'Google Business Live Center'} sub="Live Center vorbereitet für Google Business Profile API"/><div className="grid4"><Metric label="Sterne" value={g.rating||0}/><Metric label="Bewertungen" value={g.reviews_count||0}/><Metric label="Lokaler Rang" value={`#${g.local_rank||'-'}`}/><Metric label="Profilscore" value={`${g.profile_score||0}%`}/></div><div className="grid4"><Metric label="Anrufe" value={g.calls||0}/><Metric label="Wegbeschreibungen" value={g.directions||0}/><Metric label="Websiteklicks" value={g.website_clicks||0}/><Metric label="Fotoaufrufe" value={g.photo_views||0}/></div></>}
function CustomerSEO({store,cid}:any){const seo=store.data.seo_snapshots.filter((s:any)=>s.customer_id===cid);return <><GoogleBusiness store={store} cid={cid}/><Card title="SEO Entwicklung"><SEOChart rows={seo.map((s:any)=>({label:new Date(s.created_at).toLocaleDateString('de-DE',{month:'short'}),traffic:s.organic_traffic,impressions:s.impressions,keywords:s.top10_keywords}))}/></Card><Heatmap store={store} cid={cid} customer/></>}
function ReviewsQR({store,cid,role}:any){const [qr,setQr]=useState({customer_id:cid,title:'',internal_from:1,internal_to:3,google_from:4,google_to:5,internal_email:'',google_review_url:store.data.customers.find((c:any)=>c.id===cid)?.google_review_url||''});const reviews=store.data.reviews.filter((r:any)=>r.customer_id===cid);function suggestion(r:any){const hit=store.data.review_keywords.find((k:any)=>r.text?.toLowerCase().includes(k.keyword.toLowerCase()));return hit?.reply_template||'Danke für Ihr Feedback. Wir nehmen das ernst und melden uns zeitnah.'}return <><Head title="Reviews & QR" sub={role==='admin'?'QR Codes nur im Admin erstellbar.':'Bewertungen und Antwortvorschläge.'}/>{role==='admin'&&<Card title="QR Kampagne erstellen" action={<button className="btn" onClick={()=>store.create('qr_campaigns',qr)}>QR Code generieren</button>}><input className="input" placeholder="Titel" onChange={e=>setQr({...qr,title:e.target.value})}/><input className="input" placeholder="Interne Feedback E-Mail" onChange={e=>setQr({...qr,internal_email:e.target.value})}/><div className="row"><input className="input" type="number" value={qr.internal_from} onChange={e=>setQr({...qr,internal_from:Number(e.target.value)})}/><input className="input" type="number" value={qr.internal_to} onChange={e=>setQr({...qr,internal_to:Number(e.target.value)})}/></div><div className="row"><input className="input" type="number" value={qr.google_from} onChange={e=>setQr({...qr,google_from:Number(e.target.value)})}/><input className="input" type="number" value={qr.google_to} onChange={e=>setQr({...qr,google_to:Number(e.target.value)})}/></div></Card>}<Card title="Bewertungen">{reviews.map((r:any)=><div className="item" key={r.id}><div><b>{r.rating}★ · {r.author}</b><div className="sub">{r.text}</div>{r.rating<=3&&<div className="sub"><b>AI Vorschlag:</b> {suggestion(r)}</div>}</div><Badge type={r.rating>=4?'green':'red'}>{r.status}</Badge></div>)}</Card></>}
function Reports({store,cid}:any){const [tpl,setTpl]=useState<any>(null);async function uploadTpl(){const name=tpl?.name||prompt('Vorlagenname Word/Keynote');if(name)await store.create('report_templates',{customer_id:cid,name,file_type:name.endsWith('.key')?'keynote':'word',url:'#'})}return <><Head title="Monatsreports" action={<button className="btn" onClick={()=>store.create('monthly_reports',{customer_id:cid,title:'Monatsreport '+new Date().toLocaleDateString('de-DE',{month:'long'}),status:'Entwurf',template_name:tpl?.name||'Standardvorlage',pdf_url:'#'})}>Report erzeugen</button>}/><Card title="Vorlage hochladen"><input className="input" type="file" accept=".doc,.docx,.key,.ppt,.pptx" onChange={e=>setTpl(e.target.files?.[0])}/><button className="btn secondary" onClick={uploadTpl}>Vorlage speichern</button></Card></>}
function MediaCenter({store,cid,role,compact=false}:any){const [file,setFile]=useState<any>(null);const [type,setType]=useState('Bild');async function upload(){const name=file?.name||prompt('Dateiname');if(name){const asset={customer_id:cid,name,asset_type:type,url:'#',version:1};await store.create('media_assets',asset);await store.create('file_versions',{customer_id:cid,asset_id:asset.name,version:1,name,url:'#'})}}return <><Head title={compact?'Media':'Media Center'} sub="Drag&Drop/Storage-Struktur mit Versionierung vorbereitet." action={<button className="btn" onClick={upload}>Upload speichern</button>}/><Card title="Asset hochladen"><input className="input" type="file" onChange={e=>setFile(e.target.files?.[0])}/><select className="input" value={type} onChange={e=>setType(e.target.value)}><option>Logo</option><option>Bild</option><option>Video</option><option>Speisekarte</option><option>Social Asset</option><option>Vorher/Nachher</option></select></Card><Card title="Assets">{store.data.media_assets.filter((m:any)=>m.customer_id===cid).map((m:any)=><div className="item" key={m.id}><Editable value={m.name} onSave={(v:string)=>store.update('media_assets',m.id,{name:v})}/><Badge>{m.asset_type}</Badge></div>)}</Card></>}
function Editable({value,onSave}:any){const [edit,setEdit]=useState(false);const [v,setV]=useState(value);return edit?<input className="input" value={v} onChange={e=>setV(e.target.value)} onBlur={()=>{setEdit(false);onSave(v)}} autoFocus/>:<b onClick={()=>setEdit(true)} title="Klicken zum Bearbeiten">{value}</b>}
function LandingBuilder({store,cid}:any){return <Head title="Landingpage-Konfigurator"/>}
function Heatmap({store,cid}:any){const rows=store.data.local_seo_heatmap.filter((h:any)=>h.customer_id===cid);return <><Head title="Local SEO Heatmap Karte" sub="Kartenähnliche Ansicht mit Rankingpunkten."/><div className="mapBox">{rows.map((h:any,i:number)=><div className={`pin rank${Math.min(h.rank,9)}`} style={{left:`${18+i*28}%`,top:`${25+i*18}%`}} key={h.id}><b>#{h.rank}</b><span>{h.area}</span></div>)}</div><div className="grid3">{rows.map((h:any)=><Card key={h.id} title={h.area}><div className="metricValue">#{h.rank}</div><div className="sub">{h.keyword}</div></Card>)}</div></>}
function Booking({store,cid,role}:any){const [enabled,setEnabled]=useState(true);async function make(){await store.create('appointments',{customer_id:cid,client_name:'Neuer Termin',appointment_date:new Date().toISOString().slice(0,10),start_time:'10:00',end_time:'11:00',status:'Geplant',review_funnel_enabled:enabled});if(enabled)await store.create('notifications',{customer_id:cid,title:'Review Funnel aktiv',message:'Nach Termin wird ein Review Reminder vorbereitet.'})}return <><Head title="Booking" sub="Review Funnel beim Termin aktivierbar." action={<button className="btn" onClick={make}>Termin anlegen</button>}/><Card title="Review Funnel Automation"><label className="item"><span>Beim Termin aktivieren</span><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/></label></Card><Card title="Termine">{store.data.appointments.filter((a:any)=>a.customer_id===cid).map((a:any)=><div className="item" key={a.id}><b>{a.client_name}</b><Badge type={a.review_funnel_enabled?'green':'purple'}>{a.review_funnel_enabled?'Review Funnel aktiv':'ohne Funnel'}</Badge></div>)}</Card></>}
function BillingRuns({store,cid}:any){const [enabled,setEnabled]=useState(true);async function runNow(){const rule=store.data.recurring_billing_rules.find((r:any)=>r.customer_id===cid);await store.create('invoices',{customer_id:cid,invoice_number:'AUTO-'+Date.now(),service_type:`Automatischer Rechnungslauf ${rule?.package_name||''}`,amount:rule?.amount||499,status:'Offen'})}return <><Head title="Automatische Rechnungsläufe" action={<button className="btn" onClick={runNow}>Jetzt Rechnungslauf starten</button>}/><Card title="Regeln">{store.data.recurring_billing_rules.filter((r:any)=>r.customer_id===cid).map((r:any)=><div className="item" key={r.id}><div><b>{r.package_name}</b><div className="sub">{r.interval} · nächster Lauf {r.next_run}</div></div><button className="btn secondary" onClick={()=>store.update('recurring_billing_rules',r.id,{enabled:!r.enabled})}>{r.enabled?'Aktiv':'Inaktiv'}</button></div>)}</Card></>}
function Tickets(){return <Head title="Tickets"/>}
function Packages({store,cid,role}:any){return <Head title="Pakete"/>}
function Notifications({store,cid,role}:any){return <NotificationCenter store={store} cid={cid} role={role} close={()=>{}}/>}
