
require("dotenv").config();
const compression=require("compression");
const morgan=require("morgan");
const logger=require("./lib/logger");
const enterpriseRoutes=require("./routes/enterprise");
const webhookRoutes=require("./routes/webhooks");
const express=require("express"),cors=require("cors"),helmet=require("helmet"),rateLimit=require("express-rate-limit"),jwt=require("jsonwebtoken"),bcrypt=require("bcryptjs"),{nanoid}=require("nanoid"),QRCode=require("qrcode");
const dbx=require("./lib/db");const{auth,requireAdmin}=require("./middleware/auth");
const app=express();app.use(helmet());app.use(compression());app.use(morgan("combined"));app.use(cors({origin:process.env.APP_URL||"http://localhost:3000"}));app.use(express.json({limit:"2mb"}));app.use(rateLimit({windowMs:15*60*1000,limit:700,standardHeaders:true,legacyHeaders:false}));
const JWT_SECRET=process.env.JWT_SECRET||"please-change-this-secret";
function write(db){dbx.write(db)}function getClient(db,slug){return db.clients.find(c=>c.slug===slug)}function requireClient(req,res,next){const db=dbx.read();const c=getClient(db,req.params.slug);if(!c)return res.status(404).json({message:"Kunde nicht gefunden"});req.db=db;req.client=c;next()}function filter(arr,id){return(arr||[]).filter(x=>x.clientId===id)}function ok(res,d){res.json(d)}
app.use("/api/enterprise", enterpriseRoutes);
app.use("/api/webhooks", webhookRoutes);
app.use("/uploads", express.static(require("path").join(__dirname, "..", "uploads")));
app.get("/api/health",(req,res)=>ok(res,{ok:true,name:"Mecklenburg Marketing OS",mode:"1to1-live-build"}));
app.post("/api/auth/login",(req,res)=>{const db=dbx.read();const u=db.users.find(x=>x.email===req.body.email);if(!u||!bcrypt.compareSync(req.body.password,u.passwordHash))return res.status(401).json({message:"Ungültige Login-Daten"});ok(res,{token:jwt.sign({id:u.id,email:u.email,role:u.role,name:u.name},JWT_SECRET,{expiresIn:"7d"})})});
app.get("/api/agency/stats",auth,requireAdmin,(req,res)=>{const db=dbx.read();ok(res,{clients:db.clients.length,activeModules:db.clients.reduce((s,c)=>s+Object.values(c.modules||{}).filter(Boolean).length,0),reviews:db.reviews.length,leads:db.leads.length})});
app.get("/api/clients",auth,requireAdmin,(req,res)=>ok(res,dbx.read().clients));
app.post("/api/clients",auth,requireAdmin,(req,res)=>{const db=dbx.read();const c={id:nanoid(),...req.body,demoRevenue:99,subscriptionStatus:"trial",googleReviewLink:"https://google.com",modules:dbx.defaultModules(["social","portal","reviews"]),createdAt:dbx.now()};db.clients.push(c);write(db);ok(res,c)});
app.get("/api/clients/:slug",auth,(req,res)=>{const db=dbx.read();const c=getClient(db,req.params.slug);if(!c)return res.status(404).json({message:"Kunde nicht gefunden"});ok(res,c)});
app.patch("/api/clients/:id/modules",auth,requireAdmin,(req,res)=>{const db=dbx.read();const c=db.clients.find(x=>x.id===req.params.id);if(!c)return res.status(404).json({message:"Kunde nicht gefunden"});c.modules[req.body.moduleKey]=!!req.body.enabled;write(db);ok(res,c)});
app.get("/api/employees",auth,requireAdmin,(req,res)=>ok(res,dbx.read().employees));
app.post("/api/employees",auth,requireAdmin,(req,res)=>{const db=dbx.read();const e={id:nanoid(),...req.body,status:"Aktiv",createdAt:dbx.now()};db.employees.push(e);db.users.push({id:nanoid(),name:e.name,email:e.email,passwordHash:bcrypt.hashSync(req.body.password||"start123",10),role:e.role});write(db);ok(res,e)});
app.post("/api/scraper/search",auth,requireAdmin,(req,res)=>{const q=req.body.query||"Lokale Unternehmen";ok(res,[1,2,3,4,5,6,7,8].map(i=>({id:nanoid(),company:`${q} Betrieb ${i}`,category:q,phone:`0381 0000${i}`,email:`kontakt${i}@beispiel.de`,rating:(4+i/10).toFixed(1),website:`https://beispiel${i}.de`,status:"Verifiziert"})))});
app.get("/api/public/client/:slug",(req,res)=>{const db=dbx.read();const c=getClient(db,req.params.slug);if(!c)return res.status(404).json({message:"Kunde nicht gefunden"});ok(res,{name:c.name,slug:c.slug,googleReviewLink:c.googleReviewLink})});
app.post("/api/public/reviews",(req,res)=>{const db=dbx.read();const c=getClient(db,req.body.clientSlug);if(!c)return res.status(404).json({message:"Kunde nicht gefunden"});const r={id:nanoid(),clientId:c.id,rating:req.body.rating||3,name:req.body.name||"",phone:req.body.phone||"",message:req.body.message||"",createdAt:dbx.now(),status:req.body.rating>=4?"google_redirect":"internal"};db.reviews.push(r);write(db);ok(res,r)});
app.get("/api/client/:slug/reviews",auth,requireClient,(req,res)=>ok(res,filter(req.db.reviews,req.client.id)));
app.get("/api/client/:slug/leads",auth,requireClient,(req,res)=>ok(res,filter(req.db.leads,req.client.id)));
app.post("/api/client/:slug/leads",auth,requireClient,(req,res)=>{const item={id:nanoid(),clientId:req.client.id,...req.body,createdAt:dbx.now()};req.db.leads.push(item);write(req.db);ok(res,item)});
app.delete("/api/client/:slug/leads/:id",auth,requireClient,(req,res)=>{req.db.leads=req.db.leads.filter(x=>x.id!==req.params.id);write(req.db);ok(res,{ok:true})});
app.get("/api/client/:slug/bookings",auth,requireClient,(req,res)=>ok(res,filter(req.db.bookings,req.client.id)));
app.post("/api/client/:slug/bookings",auth,requireClient,(req,res)=>{const item={id:nanoid(),clientId:req.client.id,...req.body,status:"bestätigt",createdAt:dbx.now()};req.db.bookings.push(item);write(req.db);ok(res,item)});
app.get("/api/client/:slug/social-posts",auth,requireClient,(req,res)=>ok(res,filter(req.db.socialPosts,req.client.id)));
app.post("/api/client/:slug/social-posts",auth,requireClient,(req,res)=>{const item={id:nanoid(),clientId:req.client.id,status:"geplant",...req.body,createdAt:dbx.now()};req.db.socialPosts.push(item);write(req.db);ok(res,item)});
app.patch("/api/client/:slug/social-posts/:id/publish",auth,requireClient,(req,res)=>{const item=req.db.socialPosts.find(x=>x.id===req.params.id);item.status="veröffentlicht";item.publishedAt=dbx.now();write(req.db);ok(res,item)});
app.get("/api/client/:slug/outreach",auth,requireClient,(req,res)=>ok(res,filter(req.db.outreach,req.client.id)));
app.post("/api/client/:slug/outreach",auth,requireClient,(req,res)=>{const item={id:nanoid(),clientId:req.client.id,status:"geplant",opens:0,clicks:0,...req.body,createdAt:dbx.now()};req.db.outreach.push(item);write(req.db);ok(res,item)});
app.get("/api/client/:slug/reputation-alerts",auth,requireClient,(req,res)=>ok(res,filter(req.db.reputationAlerts,req.client.id)));
app.patch("/api/client/:slug/reputation-alerts/:id/resolve",auth,requireClient,(req,res)=>{const item=req.db.reputationAlerts.find(x=>x.id===req.params.id);item.status="erledigt";item.severity="resolved";write(req.db);ok(res,item)});
app.get("/api/client/:slug/reports",auth,requireClient,(req,res)=>ok(res,filter(req.db.reports,req.client.id)));
app.post("/api/client/:slug/reports/generate",auth,requireClient,(req,res)=>{const r={id:nanoid(),clientId:req.client.id,title:`Monatsreport ${new Date().toLocaleDateString("de-DE")}`,summary:"Leads, Bewertungen, SEO und Kampagnen haben sich positiv entwickelt. Dieser Report wurde automatisch aus Demo-Daten generiert.",status:"erstellt",createdAt:dbx.now()};req.db.reports.unshift(r);write(req.db);ok(res,r)});
app.get("/api/client/:slug/qr-campaigns",auth,requireClient,(req,res)=>ok(res,filter(req.db.qrCampaigns,req.client.id)));
app.post("/api/client/:slug/qr-campaigns",auth,requireClient,async(req,res)=>{const target=req.body.targetUrl||"https://example.com";const qrDataUrl=await QRCode.toDataURL(target);const item={id:nanoid(),clientId:req.client.id,scans:0,qrDataUrl,...req.body,targetUrl:target,createdAt:dbx.now()};req.db.qrCampaigns.push(item);write(req.db);ok(res,item)});
app.patch("/api/client/:slug/qr-campaigns/:id/scan",auth,requireClient,(req,res)=>{const item=req.db.qrCampaigns.find(x=>x.id===req.params.id);item.scans=(item.scans||0)+1;write(req.db);ok(res,item)});
app.get("/api/client/:slug/onboarding",auth,requireClient,(req,res)=>ok(res,filter(req.db.onboarding,req.client.id)));
app.patch("/api/client/:slug/onboarding/:id",auth,requireClient,(req,res)=>{const s=req.db.onboarding.find(x=>x.id===req.params.id);s.done=!s.done;write(req.db);ok(res,s)});
app.post("/api/client/:slug/sales-assistant",auth,requireClient,(req,res)=>ok(res,{answer:`AI-Vorschlag für ${req.client.name}: ${req.body.prompt}\\n\\nEmpfohlene Positionierung: Verkaufe mehr Bewertungen, weniger Verwaltungsaufwand und planbare Anfragen. Paketvorschlag: Growth für 299€/Monat + 499€ Setup.`}));
app.get("/api/client/:slug/proposals",auth,requireClient,(req,res)=>ok(res,filter(req.db.proposals,req.client.id)));
app.post("/api/client/:slug/proposals",auth,requireClient,(req,res)=>{const p={id:nanoid(),clientId:req.client.id,status:"Entwurf",...req.body,createdAt:dbx.now()};req.db.proposals.unshift(p);write(req.db);ok(res,p)});
app.patch("/api/client/:slug/proposals/:id/status",auth,requireClient,(req,res)=>{const p=req.db.proposals.find(x=>x.id===req.params.id);p.status=req.body.status;write(req.db);ok(res,p)});
app.post("/api/integrations/test/:provider",auth,(req,res)=>ok(res,{provider:req.params.provider,configured:false,message:"Provider-Platzhalter aktiv. API-Key in .env setzen."}));
app.listen(process.env.PORT||4000,()=>console.log("Mecklenburg Marketing OS 1:1 Live Build API läuft auf http://localhost:4000"));
