'use client'
import { useMemo, useState } from 'react'
import { Download, FileSearch, RefreshCw } from 'lucide-react'
import { AdminOnly } from '@/components/security/RoleGate'
import { businessToolsClient } from '@/lib/businessToolsClient'
function statusFromScore(score: number) { if (score < 55) return 'kritisch'; if (score < 78) return 'bedingt'; return 'stark' }
function statusColor(status: string) { if (status === 'stark') return '#16a34a'; if (status === 'bedingt') return '#f59e0b'; return '#e11d48' }
function htmlForAudit(audit: any, businessName: string, city: string) { const status = statusFromScore(Number(audit?.score || 0)); const findings = Array.isArray(audit?.findings) ? audit.findings : []; return `<main style="font-family:Arial,sans-serif;padding:42px;color:#0f172a"><section style="border-bottom:6px solid #2563eb;padding-bottom:22px;margin-bottom:28px"><p style="letter-spacing:.14em;text-transform:uppercase;color:#2563eb;font-weight:800">Google-only Mini Audit</p><h1 style="font-size:38px;margin:0">${businessName}</h1><p style="color:#64748b;font-size:18px">${city} · öffentlich sichtbare Google-Daten</p></section><section style="display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-bottom:26px"><div style="border:1px solid #e2e8f0;border-radius:18px;padding:22px"><div style="font-size:44px;font-weight:900">${audit?.score ?? '—'}<span style="font-size:18px;color:#64748b">/100</span></div><p style="margin:0;color:#64748b">Sichtbarkeits-Score</p></div><div style="border:1px solid #e2e8f0;border-radius:18px;padding:22px"><div style="font-size:28px;font-weight:900;color:${statusColor(status)}">${status}</div><p style="margin:0;color:#64748b">automatisch berechneter Status</p></div></section><section style="border:1px solid #e2e8f0;border-radius:18px;padding:22px;margin-bottom:22px"><h2>Kurzeinschätzung</h2><p>${audit?.summary || 'Das Profil wurde anhand öffentlich sichtbarer Google-Daten geprüft.'}</p></section><section style="border:1px solid #e2e8f0;border-radius:18px;padding:22px"><h2>Auffälligkeiten</h2><ul>${findings.map((f: any) => `<li>${typeof f === 'string' ? f : f?.label || JSON.stringify(f)}</li>`).join('')}</ul></section><p style="color:#94a3b8;margin-top:34px;font-size:12px">Ohne MMOS-, CRM-, QR-, Loyalty- oder Kundendaten.</p></main>` }
export default function MiniAuditGeneratorPage() {
  const [businessName, setBusinessName] = useState(''); const [city, setCity] = useState(''); const [audit, setAudit] = useState<any>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const status = useMemo(() => audit ? statusFromScore(Number(audit.score || 0)) : '', [audit])
  async function runAudit() { setBusy(true); setError(''); setAudit(null); try { const result: any = await businessToolsClient.googleBusinessAudit({ business_name: businessName.trim(), city: city.trim(), source: 'google_public_only', includeMmosData: false }); setAudit(result.audit || result) } catch (e: any) { setError(e?.message || 'Mini Audit konnte nicht erstellt werden.') } finally { setBusy(false) } }
  async function downloadPdf() { if (!audit) return; const blob = await businessToolsClient.renderPdf({ title: `Mini Audit ${businessName}`, filename: `mini-audit-${businessName || 'betrieb'}.pdf`, html: htmlForAudit(audit, businessName, city) }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `mini-audit-${businessName || 'betrieb'}.pdf`; a.click(); URL.revokeObjectURL(url) }
  return <AdminOnly><main className="adminPage"><header className="adminHeader"><h1><FileSearch size={22} style={{ verticalAlign: 'middle', marginRight: 6 }} /> Mini Audit Generator</h1><p>Internes Akquise-Tool: Google-only, ohne MMOS-, QR-, Loyalty-, CRM- oder Kundendaten.</p></header>{error && <div className="adminAlert">{error}</div>}<section className="adminCard"><h2>Google-only Audit erzeugen</h2><div className="adminGrid2"><label className="adminLabel">Betriebsname<input className="adminInput" value={businessName} onChange={(e) => setBusinessName(e.target.value)} placeholder="z.B. Café Milo" /></label><label className="adminLabel">Ort<input className="adminInput" value={city} onChange={(e) => setCity(e.target.value)} placeholder="z.B. Schwerin" /></label></div><button type="button" className="adminBtn" onClick={runAudit} disabled={busy || !businessName.trim() || !city.trim()}><RefreshCw size={14} /> {busy ? 'Erstelle …' : 'Mini Audit starten'}</button><p className="adminMuted">Datenquelle: öffentliche Google-/Places-Daten. Keine Kundendaten.</p></section>{audit && <section className="adminCard"><div className="adminActions"><h2 style={{ margin: 0 }}>Ergebnis</h2><span className="adminTabSpacer" /><button type="button" className="adminBtn small" onClick={downloadPdf}><Download size={14} /> PDF herunterladen</button></div><div className="seoGrid"><div className="seoStat"><strong>{audit.score ?? '—'}</strong><span>/100 Score</span></div><div className="seoStat"><strong style={{ color: statusColor(status) }}>{status}</strong><span>Status</span></div></div>{audit.summary && <p>{audit.summary}</p>}{Array.isArray(audit.findings) && audit.findings.length > 0 && <ul className="adminMuted" style={{ paddingLeft: 16 }}>{audit.findings.map((f: any, i: number) => <li key={i}>{typeof f === 'string' ? f : f.label || JSON.stringify(f)}</li>)}</ul>}</section>}</main></AdminOnly>
}
